export const SET_REF = 'SET_REF';
export const SET_CHECKED = 'SET_CHECKED';
export const CLEAR_CHECKBOXES = 'CLEAR_CHECKBOXES';
export const REMOVE_CHECKED = 'REMOVE_CHECKED';
export const SEND_CONFIRMATION = 'SEND_CONFIRMATION';
